import React,{useState} from 'react';
import {BENZ_SYSTEMS,BENZ_DATABASES,READINESS_STATS} from '../data/benzGovernance.js';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,PieChart,Pie,Cell} from 'recharts';
const C=['#34C759','#FF9500','#007AFF','#FF3B30','#8E8E93'];const PC=['#007AFF','#34C759','#FF9500','#AF52DE','#FF3B30','#5AC8FA','#FF6B35'];
function S({l,v,u,c}){return(<div className="stat-mini"><div className="stat-mini-value" style={{color:c}}>{v}<span className="stat-mini-unit">{u}</span></div><div className="stat-mini-label">{l}</div></div>)}
const Tp=({active,payload,label})=>{if(!active||!payload?.length)return null;return(<div className="chart-tooltip"><div className="tooltip-label">{label}</div>{payload.map((p,i)=><div key={i} style={{color:p.color||p.fill,fontSize:11}}>{p.name}:<strong>{p.value}</strong></div>)}</div>)}
const TABS=['资产盘点','资产目录','资产评估','生命周期','资产报告'];
export default function AssetPanel(){const[tab,setTab]=useState(0);const s=BENZ_SYSTEMS||[];const r=READINESS_STATS||{};const dbs=BENZ_DATABASES||[];
  const scores=[{d:'生产制造',s:72,c:'#007AFF'},{d:'质量管理',s:58,c:'#34C759'},{d:'安全消防',s:45,c:'#FF9500'},{d:'人力资源',s:82,c:'#AF52DE'},{d:'财务成本',s:51,c:'#FF3B30'},{d:'技术支持',s:44,c:'#5AC8FA'},{d:'生产计划',s:65,c:'#FF6B35'},{d:'研发工艺',s:25,c:'#8E8E93'},{d:'物流',s:30,c:'#FB923C'}];
  return(<div className="monitor-layout"><h1 className="page-title">数据资产</h1><div className="models-tabs">{TABS.map((t,i)=><button key={i} className={`models-tab${tab===i?' active':''}`} onClick={()=>setTab(i)}>{t}</button>)}</div>
    {tab===0&&<div><div className="kpi-row" style={{gridTemplateColumns:'repeat(5,1fr)'}}><S l="系统总数" v={s.length} u="个" c="#007AFF"/><S l="A档已就绪" v={r.A||0} u="个" c="#34C759"/><S l="B档部分确认" v={(r.B1||0)+(r.B2||0)} u="个" c="#FF9500"/><S l="C档手工/硬件" v={r.C||0} u="个" c="#FF3B30"/><S l="D档待确认" v={r.D||0} u="个" c="#8E8E93"/></div>
      <div className="charts-row"><div className="chart-card"><div className="chart-title">就绪度分布</div><ResponsiveContainer width="100%" height={200}><PieChart><Pie data={[{name:'A',value:r.A||0},{name:'B1',value:r.B1||0},{name:'B2',value:r.B2||0},{name:'C',value:r.C||0},{name:'D',value:r.D||0}]} cx="50%" cy="50%" innerRadius={40} outerRadius={80} dataKey="value" stroke="none">{C.map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip content={<Tp/>}/></PieChart></ResponsiveContainer><div className="chart-legend-mini">{['A','B1','B2','C','D'].map((k,i)=><span key={k}><span className="legend-dot" style={{background:C[i]}}/>{k}</span>)}</div></div>
        <div className="chart-card"><div className="chart-title">数据库覆盖</div><ResponsiveContainer width="100%" height={200}><BarChart data={dbs} layout="vertical" margin={{top:0,right:0,left:70,bottom:0}}><CartesianGrid strokeDasharray="3 3" stroke="rgba(0,0,0,0.06)"/><XAxis type="number" tick={{fontSize:9,fill:'#AEAEB2'}}/><YAxis type="category" dataKey="name" tick={{fontSize:9,fill:'#AEAEB2'}} width={65}/><Tooltip content={<Tp/>}/><Bar dataKey="count" maxBarSize={16} radius={[0,3,3,0]}>{dbs.map((_,i)=><Cell key={i} fill={PC[i]}/>)}</Bar></BarChart></ResponsiveContainer></div></div></div>}
    {tab===1&&<div className="table-wrapper"><table className="data-table"><thead><tr><th>系统</th><th>需求数</th><th>数据库</th><th>业务域</th><th>就绪度</th><th>表名</th></tr></thead><tbody>{s.map((x,i)=><tr key={i}><td style={{fontWeight:600}}>{x.name}</td><td>{x.demand}</td><td style={{fontSize:10}}>{x.db}</td><td style={{fontSize:10}}>{x.domains}</td><td style={{color:x.readiness==='A'?'#34C759':x.readiness.includes('B')?'#FF9500':x.readiness==='C'?'#FF3B30':'#8E8E93',fontWeight:600}}>{x.readiness}</td><td style={{fontSize:9}}>{(x.tables||[]).slice(0,3).join(' / ')}</td></tr>)}</tbody></table></div>}
    {tab===2&&<div><div className="kpi-row" style={{gridTemplateColumns:'repeat(4,1fr)'}}><S l="总资产价值分" v="68" u="分" c="#007AFF"/><S l="A档覆盖率" v="35" u="%" c="#34C759"/><S l="已认证数据集" v="24" u="张表" c="#FF9500"/><S l="待完善资产" v="44" u="系统" c="#FF3B30"/></div>
      <div className="chart-card" style={{marginTop:10}}><div className="chart-title">业务域资产就绪度排名</div><ResponsiveContainer width="100%" height={240}><BarChart data={scores} layout="vertical" margin={{top:5,right:30,left:55,bottom:0}}><CartesianGrid strokeDasharray="3 3" stroke="rgba(0,0,0,0.06)"/><XAxis type="number" domain={[0,100]} tick={{fontSize:9,fill:'#AEAEB2'}}/><YAxis type="category" dataKey="d" tick={{fontSize:9,fill:'#AEAEB2'}} width={50}/><Tooltip content={<Tp/>}/><Bar dataKey="s" name="就绪度分" maxBarSize={16} radius={[0,3,3,0]}>{scores.map((_,i)=><Cell key={i} fill={scores[i].c}/>)}</Bar></BarChart></ResponsiveContainer></div></div>}
    {tab===3&&<div className="table-wrapper"><table className="data-table"><thead><tr><th>阶段</th><th>策略</th><th>保留期</th><th>存储类型</th><th>操作</th></tr></thead><tbody>
      <tr><td>热数据</td><td>当日生产数据</td><td>7天</td><td>SSD</td><td style={{color:'#007AFF'}}>实时查询</td></tr>
      <tr><td>温数据</td><td>月度报表</td><td>12月</td><td>HDD</td><td style={{color:'#34C759'}}>常规访问</td></tr>
      <tr><td>冷数据</td><td>历史审计日志</td><td>3年</td><td>对象存储</td><td style={{color:'#FF9500'}}>归档压缩</td></tr>
      <tr><td>销毁</td><td>手工填报Excel</td><td>1年</td><td>-</td><td style={{color:'#FF3B30'}}>物理删除</td></tr>
    </tbody></table></div>}
    {tab===4&&<div><div className="kpi-row" style={{gridTemplateColumns:'repeat(4,1fr)'}}><S l="资产健康分" v="68" u="/100" c="#007AFF"/><S l="较上月" v="+5" u="分" c="#34C759"/><S l="治理覆盖率" v="35" u="%" c="#FF9500"/><S l="待处理项" v="44" u="个" c="#FF3B30"/></div>
      <div className="table-wrapper" style={{marginTop:10}}><table className="data-table"><thead><tr><th>业务域</th><th>健康分</th><th>排名</th><th>A档系统</th><th>趋势</th></tr></thead><tbody>
        {scores.map((x,i)=><tr key={i}><td style={{fontWeight:600}}>{x.d}</td><td>{x.s}</td><td style={{fontWeight:600,color:x.c}}>#{i+1}</td><td>{Math.round(x.s/20)}</td><td style={{color:x.s>60?'#34C759':x.s>40?'#FF9500':'#FF3B30'}}>{x.s>60?'优秀':x.s>40?'良好':'待改进'}</td></tr>)}
      </tbody></table></div></div>}
  </div>);}
